A2ZPortal.UI/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using A2ZPortal.Core.Entities.Master;
using A2ZPortal.Core.Entities.Property;
using A2ZPortal.Helper;
using A2ZPortal.Infrastructure.Repository.CustomerRepository;
using A2ZPortal.Infrastructure.Repository.GenericRepository;
using A2ZPortal.Infrastructure.Repository.HomeDetailRepository;
using A2ZPortal.Infrastructure.Repository.PropertyDetailRepository;
using A2ZPortal.UI.Helper;
using A2ZPortal.UI.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;

namespace A2ZPortal.UI.Controllers
{
    [ResponseCache(Duration = 120)]
    [BreadcrumbActionFilter]
    public class HomeController : Controller
    {
        private readonly IGenericRepository<UpComingPropertyDetail, int> _iUpComingPropertyDetailGenericRepository;
        private readonly IGenericRepository<Location, int> _iLocationGenericRepository;
        private readonly IGenericRepository<SubLocation, int> _iSubLocationGenericRepository;
        private readonly IGenericRepository<PropertyStatusModel, int> _iPropertyStatusGenericRepository;
        private readonly IGenericRepository<PropertyType, int> _iPropertyTypeGenericRepository;
        private readonly IGenericRepository<BedRoom, int> _iBedRoomGenericRepository;
        private readonly IGenericRepository<BathRoom, int> _iBathRoomGenericRepository;
        private readonly IGenericRepository<Amenities, int> _iAmenitiesGenericRepository;
        private readonly IHomeDetailRepository _IHomeDetailRepository;
        private readonly IPropertyDashBoradRepository _IPropertyDashBoradRepository;
        private readonly string APIURL;
        private readonly IConfiguration _configuration;
        public HomeController(IGenericRepository<Location, int> iLocationGenericRepository,
            IGenericRepository<SubLocation, int> iSubLocationGenericRepository,
             IGenericRepository<PropertyStatusModel, int> iPropertyStatusGenericRepository,
             IGenericRepository<PropertyType, int> iPropertyTypeGenericRepository,
              IGenericRepository<BedRoom, int> iBedRoomGenericRepository,
             IGenericRepository<BathRoom, int> iBathRoomGenericRepository,
             IGenericRepository<Amenities, int> iAmenitiesGenericRepository,
             IHomeDetailRepository homeDetailRepository, IConfiguration configuration,
             IPropertyDashBoradRepository propertyDashBoradRepository,
             IGenericRepository<UpComingPropertyDetail, int> iUpComingPropertyDetailGenericRepository


            )
        {
            _iLocationGenericRepository = iLocationGenericRepository;
            _iSubLocationGenericRepository = iSubLocationGenericRepository;
            _iPropertyStatusGenericRepository = iPropertyStatusGenericRepository;
            _iPropertyTypeGenericRepository = iPropertyTypeGenericRepository;
            _iBedRoomGenericRepository = iBedRoomGenericRepository;
            _iBathRoomGenericRepository = iBathRoomGenericRepository;
            _iAmenitiesGenericRepository = iAmenitiesGenericRepository;
            APIURL = configuration.GetSection("APIURL").Value;
            _IHomeDetailRepository = homeDetailRepository;
            _iUpComingPropertyDetailGenericRepository = iUpComingPropertyDetailGenericRepository;
            _IPropertyDashBoradRepository = propertyDashBoradRepository;

        }
        private async Task PopulateViewBag()
        {
            var taskRecentProperty = _IHomeDetailRepository.GetRecentPropertyDetail();
            var taskPropertyLocationWiseCount = _IHomeDetailRepository.GetPropertyLocatonWiseCount();
            var taskRecentPropertyDetails = _IPropertyDashBoradRepository.GetRecentPropertyDetail(1, 10);
            var taskPropertyStatus = _iPropertyStatusGenericRepository.GetList(x => x.IsActive && !x.IsDeleted);
            var taskBedRooms = _iBedRoomGenericRepository.GetList(x => x.IsActive && !x.IsDeleted);
            var taskBathRooms = _iBathRoomGenericRepository.GetList(x => x.IsActive && !x.IsDeleted);
            var taskPropertyType = _iPropertyTypeGenericRepository.GetList(x => x.IsActive && !x.IsDeleted);
            var taskLocation = _iLocationGenericRepository.GetList(x => x.IsActive && !x.IsDeleted);
            var taskSubLocation = _iSubLocationGenericRepository.GetList(x => x.IsActive && !x.IsDeleted);
            var taskAnemities = _iAmenitiesGenericRepository.GetList(x => x.IsActive && !x.IsDeleted);

            await Task.WhenAll
                            (taskPropertyLocationWiseCount,
                            taskRecentProperty,
                            taskRecentPropertyDetails, taskPropertyStatus, taskBedRooms,
                            taskBathRooms, taskPropertyType, taskLocation, taskSubLocation, taskAnemities);

            var recentProperties = taskRecentProperty.Result;

            recentProperties.ForEach(x =>
            {
                x.ImagePath = APIURL + x.ImagePath;

            });

            var recentPropertyDetails = taskRecentPropertyDetails.Result;
            recentPropertyDetails.ForEach(x =>
            {
                x.ImagePath = APIURL + x.ImagePath;
            });


            ViewBag.PropertyRecentDetail = recentPropertyDetails;
            ViewBag.PropertyLocationCount = taskPropertyLocationWiseCount.Result;
            ViewBag.PropertyImage = recentProperties;
            ViewBag.PropertyStatus = taskPropertyStatus.Result.Entities;
            ViewBag.BedRoom = taskBedRooms.Result.Entities;
            ViewBag.BathRoom = taskBathRooms.Result.Entities;
            ViewBag.PropertyType = taskPropertyType.Result.Entities;
            ViewBag.Location = taskLocation.Result.Entities;
            ViewBag.SubLocation = taskSubLocation.Result.Entities;
            ViewBag.Amenities = taskAnemities.Result.Entities;
        }


        public async Task<IActionResult> Index()
        {
            ViewData["Title"] = "| Index";
            await PopulateViewBag();
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        [HttpPost]
        public JsonResult Search(string prefix)
        {
            var taskLocation = _iLocationGenericRepository.GetList(x => x.IsActive && !x.IsDeleted).Result.Entities.Where(p => p.LocationName.Contains(prefix)).ToList();
            return Json(taskLocation);
        }
        public async Task<IActionResult> SeachBoxPartial()
        {
            await PopulateViewBag();
            return PartialView(ViewPageHelper.InstanceHelper.GetPathDetail("Home", "SeachMaster"));
        }
        public async Task<IActionResult> UpComingProject()
        {
            var taskPropertyStatus = await _iUpComingPropertyDetailGenericRepository.GetList(x => x.IsActive && !x.IsDeleted);

            taskPropertyStatus.Entities.ToList().ForEach(item =>
            {
                item.ImagePath = APIURL + item.ImagePath;
            });
            return PartialView(ViewPageHelper.InstanceHelper.GetPathDetail("Home", "UpComingProject"), taskPropertyStatus.Entities.LastOrDefault());
        }
        public async Task<IActionResult> FeaturedProperty(int pageIndex)
        {
            return await Task.Run(() => ViewComponent("Featured", pageIndex));
        }
        public async Task<IActionResult> TestimonialProperty()
        {
            return await Task.Run(() => ViewComponent("Testimonials"));
        }
    }
}

A2ZPortal.UI/Controllers/ViewComponents/FeaturedViewComponent.cs
using A2ZPortal.Core.Entities.Master;
using A2ZPortal.Infrastructure.Repository.GenericRepository;
using A2ZPortal.Infrastructure.Repository.PropertyDetailRepository;
using A2ZPortal.UI.Helper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace A2ZPortal.UI.Controllers.ViewComponents
{
    [BreadcrumbActionFilter]
    public class FeaturedViewComponent : ViewComponent
    {
        private readonly IPropertyDashBoradRepository _IPropertyDashBoardRepository;
        private readonly IConfiguration _configuration;
        private readonly string APIURL = string.Empty;
        public FeaturedViewComponent(IPropertyDashBoradRepository propertyDashBoradRepository, IConfiguration configuration)
        {
            _IPropertyDashBoardRepository = propertyDashBoradRepository;
            _configuration = configuration;
            APIURL = configuration.GetSection("APIURL").Value;
        }
        public async Task<IViewComponentResult> InvokeAsync(int pageIndex=1)
        {
            var models = await _IPropertyDashBoardRepository.GetPropertyFeatureDetails(pageIndex, 6);
            
            models.ForEach(item =>
            {
                item.ImagePath = APIURL + item.ImagePath;
            });
            return await Task.FromResult((IViewComponentResult)View("_FeaturedProperty", models));
        }

      

    }
}

A2ZPortal.UI/Controllers/ViewComponents/PropertySearchViewComponent.cs
using A2ZPortal.Core.Entities.Master;
using A2ZPortal.Infrastructure.Repository.CustomerRepository;
using A2ZPortal.Infrastructure.Repository.GenericRepository;
using A2ZPortal.Infrastructure.Repository.HomeDetailRepository;
using A2ZPortal.Infrastructure.Repository.PropertyDetailRepository;
using A2ZPortal.UI.Helper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace A2ZPortal.UI.Controllers.ViewComponents
{
    [BreadcrumbActionFilter]
    public class PropertySearchViewComponent:ViewComponent
    {
        private readonly IGenericRepository<Location, int> _iLocationGenericRepository;
        private readonly IGenericRepository<PropertyStatusModel, int> _iPropertyStatusGenericRepository;
        private readonly IGenericRepository<PropertyType, int> _iPropertyTypeGenericRepository;
        private readonly IGenericRepository<BedRoom, int> _iBedRoomGenericRepository;
        private readonly IGenericRepository<BathRoom, int> _iBathRoomGenericRepository;
        private readonly IGenericRepository<Amenities, int> _iAmenitiesGenericRepository;
        public PropertySearchViewComponent(IGenericRepository<Location, int> iLocationGenericRepository,
             IGenericRepository<PropertyStatusModel, int> iPropertyStatusGenericRepository,
             IGenericRepository<PropertyType, int> iPropertyTypeGenericRepository,
              IGenericRepository<BedRoom, int> iBedRoomGenericRepository,
             IGenericRepository<BathRoom, int> iBathRoomGenericRepository,
             IGenericRepository<Amenities, int> iAmenitiesGenericRepository


            )
        {
            _iLocationGenericRepository = iLocationGenericRepository;
            _iPropertyStatusGenericRepository = iPropertyStatusGenericRepository;
            _iPropertyTypeGenericRepository = iPropertyTypeGenericRepository;
            _iBedRoomGenericRepository = iBedRoomGenericRepository;
            _iBathRoomGenericRepository = iBathRoomGenericRepository;
            _iAmenitiesGenericRepository = iAmenitiesGenericRepository;

        }
        public async Task<IViewComponentResult> InvokeAsync()
        {            
            await PopulateViewBag();
            return await Task.FromResult((IViewComponentResult)View("_PropertySearch" ));
        }
        private async Task PopulateViewBag()
        {
            var taskPropertyStatus = _iPropertyStatusGenericRepository.GetList(x => x.IsActive && !x.IsDeleted);
            var taskBedRooms = _iBedRoomGenericRepository.GetList(x => x.IsActive && !x.IsDeleted);
            var taskBathRooms = _iBathRoomGenericRepository.GetList(x => x.IsActive && !x.IsDeleted);
            var taskPropertyType = _iPropertyTypeGenericRepository.GetList(x => x.IsActive && !x.IsDeleted);
            var taskLocation = _iLocationGenericRepository.GetList(x => x.IsActive && !x.IsDeleted);
            var taskAnemities = _iAmenitiesGenericRepository.GetList(x => x.IsActive && !x.IsDeleted);
            ViewBag.PropertyStatus = taskPropertyStatus.Result.Entities;
            ViewBag.BedRoom = taskBedRooms.Result.Entities;
            ViewBag.BathRoom = taskBathRooms.Result.Entities;
            ViewBag.PropertyType = taskPropertyType.Result.Entities;
            ViewBag.Location = taskLocation.Result.Entities;
            ViewBag.Amenities = taskAnemities.Result.Entities;
        }

    }
}

A2ZPortal.UI/Views/Home/Index.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";

}
<style>
    /* #popup .modal-dialog {
                min-height: calc(100vh);
                display: flex;
                flex-direction: column;
                justify-content: center;
                overflow: auto;
                padding-top: 30px;
            }

            #popup .modal-content {
                width: 75%;
                margin: auto
            }

            #popup img {
                width: 400px
            }

            #popup #close {
                position: absolute;
                right: -15px;
                top: -15px;
                background: #7b0211;
                border-radius: 50%;
                padding: 0 5px 5px 5px
            }
        */


    h5 {
        font-size: 16px;
        font-weight: bold
    }

    .form-inline .form-control, .select2-container--default .select2-selection--single .select2-selection__placeholder, .select2-selection__rendered {
        font-size: 14px
    }
</style>
<section class="custom-form" id='form-1'>
    @await Component.InvokeAsync("PropertySearch")
</section>
@await Component.InvokeAsync("Featured")

<section class="popular mt-5">
    <div class="border border-1">
        <div class="container">
            <div class="row">
                <div class="col-md-8 my-3">
                    <img src="~/A2Z-contents/img/elite.jpeg" alt="" class="img-fluid" />
                </div>
                <div class="col-md-4">
                    <div class="mt-md-5 mb-3">
                        <h2 class="mt-md-5 pt-md-5">Elite Residence, Dubai Marina</h2>
                        <p class="my-3">
                            Residential tower
                            83 floors of residential apartments/ 4 parking floors/ 4 basement levels/ 2 health clubs/ state of the art business centre
                        </p>
                        <a type="button" class="btn btn-primary" asp-action="GetPropertyDetail" asp-controller="PropertyDetails" asp-route-id=1002>Know More</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>


<section class="best-deals my-5">
    <div class="container">
        <h2 class="text-center mb-5">Featured Properties For Rent</h2>
        <div class="row">
            <div class="owl-carousel owl-theme " id="owl-carousel-0">
                @foreach (var data in ((IEnumerable<A2ZPortal.Core.ViewModel.PropertyDetail.RecentPropertyDetail>)ViewBag.PropertyRecentDetail).GroupBy(x => x.PropertyId).OrderByDescending(x => x.FirstOrDefault().PropertyId))
                {
                    <div class="item">
                        <div class="border">
                            <img src="@data.First().ImagePath" alt="" class="img-fluid" style="width:370px; height:300px">
                            <div class="p-4">
                                <h5>@data.First().PropertyName </h5>

                                <button type="button" class="btn btn-primary disabled">
                                    @string.Format("{0:0}", data.First().Price) AED
                                </button>
                                @if (data.First().PropertyType == "Rent")
                                {
                                    <span>Per Month</span>
                                }
                                <a type="button" class="btn btn-primary" asp-action="GetPropertyDetail" title="@data.First().PropertyName" asp-route-id="@data.First().PropertyId" asp-controller="PropertyDetails">View Details</a>
                                <a asp-action="AddToFavourite" asp-controller="CustomerTransaction"
                                   asp-route-propId="@data.First().PropertyId" class="btn btn-primary"><i class="fa fa-heart"></i></a>
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</section>

<div class="add" id="UpcomingProject-modal" style="display:none">
    <button type="button" class="close" id="close-add">&times;</button>
    <div id="UpcomingProject-body">
    </div>
</div>


<div class="vedpopup" id="popid"  style="display:block; height:300px; width:300px; border:solid 1px black; position:fixed; top: 210px; left: 0; z-index: 990;">
    <button type="button" id="closeId" value="close" style="position: relative; right: -277px; z-index:999; background:#7b0211; color:#fff">X</button>
    <div id="vediodiv">
         <video autoplay loop style="height: 300px; width:298px; position:relative; top:-31px;">
        <source src="~/A2Z-contents/WhatsappVedioHome.mp4" type="video/mp4"/>
    </video>
    </div>
</div>

<script>
    $(document).ready(function () {
        $("#closeId").click(function () {
            $("#popid").hide();
         });
    });
</script>

<script>
    $(document).ready(function () {
        $('.owl-theme').owlCarousel({
            margin: 10,
            nav: true,
            loop: true,
            slideBy: 1,
            autoplay: true,
            autoplayTimeout: 3000,
            rtl: true,
            autoplayHoverPause: true,
            navText: ['<i class="fa fa-chevron-left"></i>', '<i class="fa fa-chevron-right"></i>'],
            responsive: {
                0: {
                    items: 1
                },
                768: {
                    items: 2
                },
                1200: {
                    items: 3
                }
            }
        });
        if (sessionStorage.getItem("isFirst") == null) {

            sessionStorage.setItem("isFirst", 1);

            $.get("/Home/UpComingProject",
                function (data) {
                    debugger;
                    $("#UpcomingProject-body").html(data);
                    $("#UpcomingProject-modal").show('slow');

                });

            $("header, section, footer").addClass('overlay');

            $("#close-add").click(function () {
                $("#UpcomingProject-modal").hide();
                $("header, section, footer").removeClass('overlay');
            });
        }
    });
</script>

A2ZPortal.UI/Views/Home/UpComingProject.cshtml
@model A2ZPortal.Core.Entities.Property.UpComingPropertyDetail
 
@* 
<img src="@Model.ImagePath" alt="" class="img-fluid">*@

@*Local Path*@

<img src="~/A2Z-contents/Whatsapp Image for model.jpg" alt="" class="img-fluid">
<br>
 <a asp-action="GetPropertyDetail" asp-controller="UpcomingProject" asp-route-Id="@Model.Id" class="btn btn-secondary btn-block mt-3">Click Here </a>