A2ZAdmin.UI/Controllers/ViewComponents/FilterViewComponent.cs
using A2ZPortal.Infrastructure.Repository.UserManagement;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace A2ZAdmin.UI.Controllers.ViewComponents
{
    [ViewComponent(Name = "Filter")]
    public class FilterViewComponent:ViewComponent
    {
        private readonly IUserManagementRepository _IUserManagementRepository;

        public FilterViewComponent(IUserManagementRepository iUserManagementRepository)
        {
            _IUserManagementRepository = iUserManagementRepository;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var model =(await  _IUserManagementRepository.GetSubModuleDetails()).OrderBy(x=>x.SubModuleName).ToList();
            return await Task.FromResult((IViewComponentResult)View("_FilterSharedPartial", model));
        }
    }
}

A2ZAdmin.UI/Views/NumberOfParkingMaster/NumberOfParkingMasterCreate.cshtml
@model A2ZPortal.Core.Entities.Master.NumberOfParking


<script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
<script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>

<form id="form" method="post" data-ajax="true" data-ajax-method="post"
      asp-action="PostCreate" asp-controller="NumberOfParkingMaster" data-ajax-success="Success" data-ajax-begin="BeginRequest">
    <div class="box-body">

        <div class="col-md-12">
            <div class="form-group">
                <input asp-for="Id" type="hidden" />
                <input asp-for="CreatedBy" type="hidden" />
                <input asp-for="CreatedDate" type="hidden" />
                <label asp-for="TotalParking">No Of Parking</label><span class="text-danger"> * </span>

                <input type="text" asp-for="TotalParking" class="form-control" />
                <span asp-validation-for="TotalParking" class="text-danger"></span>
            </div>

        </div>


    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-success pull-right"><i class="fa fa-plus"> &nbsp; Save</i></button>
        <button type="reset" class="btn btn-danger"> <i class="fa fa-refresh"> &nbsp; Cancel</i></button>
    </div>
</form>

A2ZAdmin.UI/Views/NumberOfParkingMaster/NumberOfParkingMasterDetails.cshtml
@using System.Runtime.InteropServices.ComTypes
@model IEnumerable<A2ZPortal.Core.Entities.Master.NumberOfParking>

<div id="example1_wrapper" class="dataTables_wrapper form-inline dt-bootstrap">
    <div class="row">
        <div class="col-sm-12">
            <table id="example1" class="table table-bordered table-striped dataTable" role="grid" aria-describedby="example1_info">
                <thead>
                    <tr role="row">
                        <th>No Of Parking</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var data in Model)
                    {
                        <tr>

                            <td>@data.TotalParking</td>
                            <td>
                                <button class="btn btn-primary btn-xs">
                                    <i class="fa fa-pencil" onclick="Edit(@data.Id)"></i>
                                </button>
                                <button class="btn btn-danger btn-xs" onclick="Delete(@data.Id)">
                                    <i class="fa fa-close"></i>
                                </button>
                            </td>
                        </tr>
                    }
                </tbody>

            </table>
        </div>
    </div>
</div>
<script>
    $(function () {
        $('#example1').DataTable();

    })
</script>

A2ZAdmin.UI/Views/NumberOfParkingMaster/NumberOfParkingMasterIndex.cshtml
@{
    ViewData["Title"] = "No of Parking Master";
}
<div class="content-wrapper">

    <section class="content-header">
        <h1>
            @ViewData["Header"]
            <small> @ViewData["Header"] Details</small>
        </h1>
    </section>
    <section class="content" id="divContent">
        <div class="row">
            <div class="col-md-8">
                <div class="box">
                    <div class="box-header">
                        <h3 class="box-title">No of Parking Master Details</h3>
                        <button class="btn btn-primary pull-right" onclick="Create()">
                            <i class="fa fa-plus">&nbsp;Add</i>
                        </button>
                    </div>

                    <div class="box-body">
                        <div id="divData"></div>
                    </div>
                </div>
            </div>

            <div class="col-md-4">
                @await Component.InvokeAsync("Filter")
            </div>
        </div>
    </section>
</div>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js" integrity="sha512-894YE6QWD5I59HgZOGReFYm4dnWc1Qt5NtvYSaNcOP+u1T9qYdvdihz0PPSiiqn/+/3e7Jo4EaG7TubfWGUrMQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

<environment include="Production">
    <script src="~/CustomJavaScript/NumberOfParking.js"></script>
</environment>
<environment include="Development">
    <script src="~/CustomJavaScript/NumberOfParking.js"></script>
</environment>